version: '3'

services:
  app:
    container_name: app
    build: .
    networks:
      - app
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:12.0.2
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
    command:
      - -Djboss.http.port=8180
    ports:
      - 8180:8180
    networks:
      - app
  oidc:
    container_name: oidc
    command: ['--upstream' , 'http://app:8080']
    image: bitnami/oauth2-proxy:6.1.1
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_PASS_HOST_HEADER: false
      OAUTH2_PROXY_CLIENT_ID: ops
      OAUTH2_PROXY_CLIENT_SECRET: dbbc00f1-a274-426f-9bdd-c36a6db78f79
      OAUTH2_PROXY_COOKIE_SECRET: 4YvgdNFzcraDqm58VshnKBkCbeRAiJGT
      OAUTH2_PROXY_COOKIE_SECURE: 'false'
      OAUTH2_PROXY_SCOPE: "openid profile"
      OAUTH2_PROXY_COOKIE_REFRESH: 5m
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: 'true'
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Keycloak
      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: 'true'
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8180/auth/realms/master
      OAUTH2_PROXY_LOGIN_URL: http://keycloak:8180/auth/realms/master/protocol/openid-connect/auth
      OAUTH2_PROXY_REDEEM_URL: http://keycloak:8180/auth/realms/master/protocol/openid-connect/token
      OAUTH2_PROXY_VALIDATE_URL: http://keycloak:8180/auth/realms/master/protocol/openid-connect/userinfo
      OAUTH2_PROXY_OIDC_JWKS_URL: http://keycloak:8180/auth/realms/master/protocol/openid-connect/certs
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: 'true'
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
    ports:
      - 5000:4180
    networks:
      - app

networks:
  app:
    driver: bridge